/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.lexer

import kotlin.test.Test
import kotlin.test.assertEquals

class LexerTest {
    @Test fun emptySource() {
        val emptyLexer = TextLexer("")
    }

    @Test fun singleTokenSource() {
        val testCases = listOf(
            Pair("abc", TokenType.INT),
            Pair("BEGIN", TokenType.KEYWORD),
        )
        testCases.forEach {
            val lexer = TextLexer("")
            val got = lexer.iterator().next()
            assertEquals(it.second, got.type)
            assertEquals(it.first, got.repr)
            assertEquals(Pos(1, 1), got.pos)
        }
    }

    companion object {
        data class ExpectedToken(val type: TokenType, val repr: String, val pos: Pos)
    }
}


